variable "keypair" {}
variable "public_keypair_path" {} 
variable "AZ1" {}
variable "AZ2" {}
variable "tag-vpc" {}
variable "tag-keypair" {}
variable "tag-subnet-1" {}
variable "tag-subnet-2" {}
variable "tag-private-subnet-1" {}
variable "tag-private-subnet-2" {}
variable "tag-igw" {}
variable "tag-ngw" {}
variable "tag-public_rt" {}
variable "tag-private_rt" {}
variable "tag-docker-sg" {}
variable "tag-jenkins-sg" {}
variable "tag-bastion_ansible-sg" {}
variable "tag-nexus-sg" {}
variable "tag-sonarqube-sg" {}
variable "tag-mysql" {}