variable "ami" {}
variable "instance_type" {}
variable "security_group_ids" {}
variable "subnet_id" {}
variable "key_name" {}
variable "stage-playbook" {}
variable "prod-playbook" {}
variable "stage-bashscript" {}
variable "prod-bashscript" {}
variable "private-key" {}
variable "nexus-server-ip" {}
variable "tag-ansible-server" {}